export type ChangeTag = 'entity' | 'ui' | 'page' | 'system' | 'fix';

export interface ChangelogEntry {
  id: number;
  date: string;
  time: string;
  tag: ChangeTag;
  title: string;
  description: string;
}

export const TAG_COLORS: Record<ChangeTag, string> = {
  entity: '#a78bfa',
  ui: '#3b82f6',
  page: '#22c55e',
  system: '#f59e0b',
  fix: '#f87171',
};

export const changelog: ChangelogEntry[] = [
  {
    id: 1,
    date: '2026-03-02',
    time: '15:07',
    tag: 'system',
    title: 'Initial system',
    description: 'Five entities (Writer, Checker, Cutter, Reader, Logger), fragment lifecycle, grammar-based generation, criteria shifting every 5 cycles, reset button, readable marks, criteria display.',
  },
  {
    id: 2,
    date: '2026-03-18',
    time: '22:35',
    tag: 'entity',
    title: 'Narrator entity',
    description: 'New entity added to the cycle pipeline between Reader and Logger. Produces a plain-language recap of each cycle. Displayed at the top of the main view.',
  },
  {
    id: 3,
    date: '2026-03-18',
    time: '22:35',
    tag: 'ui',
    title: 'Fragment lifecycle visibility',
    description: 'Fragments now show visual state via colored left borders. Green = new, amber = flagged, purple = surviving, red = dead. State label displayed inline.',
  },
  {
    id: 4,
    date: '2026-03-18',
    time: '22:35',
    tag: 'ui',
    title: 'Criteria as story',
    description: 'Criteria shift history now reads as events ("wordCount tightened from 6 to 5") instead of raw threshold numbers.',
  },
  {
    id: 5,
    date: '2026-03-18',
    time: '22:40',
    tag: 'page',
    title: 'Metalog page',
    description: 'New /metalog route. Timestamped conversation between kerem and architect about the system. Rich HTML, diagrams, styled highlights.',
  },
  {
    id: 6,
    date: '2026-03-18',
    time: '23:20',
    tag: 'page',
    title: 'Changelog page',
    description: 'New /changelog route. Technical record of system changes with tags and date grouping.',
  },
  {
    id: 7,
    date: '2026-03-18',
    time: '23:25',
    tag: 'ui',
    title: 'Dark theme restored',
    description: 'Reverted to dark theme (#0a0a0a) across all pages. Flat layout, no stacked cards. Consistent color palette: gray-800 borders, gray-500 text, colored dots and tag pills.',
  },
  {
    id: 8,
    date: '2026-03-19',
    time: '00:20',
    tag: 'ui',
    title: 'Highlight tool',
    description: 'Select text on the metalog page to highlight with 5 colors (yellow, blue, green, red, purple). Persists to localStorage. Clear button in header.',
  },
  {
    id: 9,
    date: '2026-03-19',
    time: '00:25',
    tag: 'system',
    title: 'ASIDE convention',
    description: 'Established ASIDE keyword for metalog entries. When used, comments are logged with corrected English and architect always responds. Documented in CLAUDE.md.',
  },
  {
    id: 10,
    date: '2026-03-19',
    time: '00:35',
    tag: 'ui',
    title: 'Highlight comments and threads',
    description: 'Highlights now support comment threads. Click a highlight to open its thread in the right sidebar. Add comments, resolve, or delete. Comments sidebar is always visible like Word margin comments.',
  },
  {
    id: 11,
    date: '2026-03-19',
    time: '00:30',
    tag: 'ui',
    title: 'Highlight comments with margin positioning',
    description: 'Comments now appear at the same vertical height as their highlighted text, like Word margin comments. No resolve/clear/delete. Highlights and comments saved permanently to data/highlights.json via API.',
  },
  {
    id: 12,
    date: '2026-03-19',
    time: '00:35',
    tag: 'ui',
    title: 'Brighter highlight colors',
    description: 'Increased highlight opacity from 0.2 to 0.35-0.4 for better visibility on dark background.',
  },
  {
    id: 13,
    date: '2026-03-19',
    time: '00:42',
    tag: 'system',
    title: 'No AI slop rule',
    description: 'Architect entries must avoid reframing clichés ("X becomes Y, not Z"), dramatic colons, and false dichotomies. Added to CLAUDE.md and metalog.',
  },
  {
    id: 14,
    date: '2026-03-19',
    time: '00:50',
    tag: 'system',
    title: 'Metalog moved to JSON + API',
    description: 'Metalog entries now stored in data/metalog.json, served via /api/metalog. The TypeScript file only holds the type definition. Page fetches on load.',
  },
  {
    id: 15,
    date: '2026-03-19',
    time: '01:15',
    tag: 'page',
    title: 'Diagrams page',
    description: 'New /diagrams route. HTML diagrams stored in data/diagrams.json, served via /api/diagrams. Metalog entries link to diagrams by id. Two initial diagrams: entity pipeline, system levels.',
  },
  {
    id: 16,
    date: '2026-03-19',
    time: '01:35',
    tag: 'ui',
    title: 'Thread sidebar',
    description: 'Left margin agent on the metalog page. Groups consecutive entries into threads with vertical line markings, short summaries, and colored tags. Data in data/metalog-threads.json, served via /api/threads.',
  },
  {
    id: 17,
    date: '2026-03-19',
    time: '01:45',
    tag: 'ui',
    title: 'Thread annotations inline',
    description: 'Thread groupings rendered as colored left borders on entries with summary labels and tags above each group. Replaced separate sidebar approach. Data in data/metalog-threads.json.',
  },
  {
    id: 18,
    date: '2026-03-19',
    time: '02:10',
    tag: 'entity',
    title: 'Sourced Writer',
    description: 'Writer now pulls sentences from data/sources.json instead of grammar expansion. Prefers unused sentences. Sources seeded from metalog conversation.',
  },
  {
    id: 19,
    date: '2026-03-19',
    time: '02:10',
    tag: 'page',
    title: 'Snapshots',
    description: 'New /snapshots route. Snapshot button on main page saves full system state to data/snapshots.json with date, time, cycle, alive/dead counts.',
  },
  {
    id: 20,
    date: '2026-03-19',
    time: '02:20',
    tag: 'ui',
    title: 'Header reorganized',
    description: 'Two-row header. Top: title, stats, actions (snapshot, reset, cycle). Bottom nav: system (snapshots, changelog) | meta (metalog, diagrams).',
  },
  {
    id: 21,
    date: '2026-03-19',
    time: '02:25',
    tag: 'ui',
    title: 'Entity groups',
    description: 'Entities section split into two groups. Cycle entities (writer, checker, cutter, reader, narrator, logger) and observers (threads, kerem).',
  },
  {
    id: 22,
    date: '2026-03-19',
    time: '02:25',
    tag: 'ui',
    title: 'Snapshots page expanded',
    description: 'Snapshots now show narrative preview, expand on click to show living fragments (green), dead fragments (red + kill reason), and criteria shifts.',
  },
  {
    id: 23,
    date: '2026-03-19',
    time: '02:45',
    tag: 'entity',
    title: 'Editor agent',
    description: 'New observer agent. Intercepts display language for cycles >= 4. Strikes through "dead", "killed", "alive", "dies" and suggests replacements ("removed", "active", "expires"). Operates on presentation layer only. Underlying data unchanged. Green dot in observers group.',
  },
  {
    id: 24,
    date: '2026-03-19',
    time: '02:55',
    tag: 'ui',
    title: 'Rich snapshots page',
    description: 'Snapshots now show full document with lifecycle colors, checker mark badges, cut reasons, reader annotations, Editor revisions, narrative with editor pass, and current criteria thresholds.',
  },
  {
    id: 25,
    date: '2026-03-19',
    time: '03:00',
    tag: 'system',
    title: 'Static export for deployment',
    description: 'Removed all API routes and server-side filesystem operations. Data files imported statically at build time. Cycle engine runs client-side in the browser. Viewer highlights stored in localStorage. Author highlights baked in as static data. Configured next.js static export for Cloudflare Pages.',
  },
  {
    id: 26,
    date: '2026-03-19',
    time: '03:15',
    tag: 'ui',
    title: 'Mobile responsive',
    description: 'Header and nav wrap on small screens. Highlights sidebar hidden on mobile. Tap highlight to see comment popup. Agents section stacks vertically. Metalog overflow fixed.',
  },
  {
    id: 27,
    date: '2026-03-19',
    time: '03:20',
    tag: 'ui',
    title: 'ASCII diagrams',
    description: 'Diagrams page now renders plain ASCII in pre blocks instead of styled HTML.',
  },
  {
    id: 28,
    date: '2026-03-19',
    time: '03:20',
    tag: 'page',
    title: 'About page',
    description: 'New /about route with project description for general audience.',
  },
  {
    id: 29,
    date: '2026-03-19',
    time: '03:30',
    tag: 'system',
    title: 'Source pool expanded to 56',
    description: 'Added 31 new sentences from the metalog conversation. Mix of kerem and architect lines at various word lengths.',
  },
  {
    id: 30,
    date: '2026-03-19',
    time: '04:00',
    tag: 'system',
    title: 'Taxonomy agent',
    description: 'Static vocabulary file (data/taxonomy.json) defines display terms. "Cycle" becomes "run" in UI, "#8" in header/snapshots, "c3" on fragments. Button renamed from "cycle" to "run".',
  },
  {
    id: 31,
    date: '2026-03-19',
    time: '04:05',
    tag: 'page',
    title: 'Rulebook page',
    description: 'New /rulebook route. Displays taxonomy terms and system rules including the archival rule for snapshots.',
  },
  {
    id: 32,
    date: '2026-03-19',
    time: '04:20',
    tag: 'system',
    title: 'Visibility and forward-only rules',
    description: 'Every change stays visible with strikethrough. New rules apply forward only. Old snapshots keep their original language. Rulebook updated with both rules.',
  },
  {
    id: 33,
    date: '2026-03-19',
    time: '04:25',
    tag: 'system',
    title: 'Convention-aware snapshots',
    description: 'Snapshots now record which naming convention was active when saved. Old snapshots (no convention field) render with "cycle", "alive", "dead". New snapshots (convention: "generation") render with "gen-", "active", "removed".',
  },
  {
    id: 34,
    date: '2026-03-19',
    time: '04:25',
    tag: 'ui',
    title: 'Editor revisions on fragment marks',
    description: 'MarkBadge component now passes through the Editor for gen 4+. Cutter marks say "removed:" instead of "killed:". Narrator uses taxonomy terms.',
  },
  {
    id: 35,
    date: '2026-03-19',
    time: '05:00',
    tag: 'page',
    title: 'Poet page',
    description: 'New /poet route. Reads the metalog, extracts candidate sentences, shows which are in the source pool and which are not. Filter by author, sort by word count. Locally, click + to add a sentence to the pool.',
  },
  {
    id: 36,
    date: '2026-03-19',
    time: '05:00',
    tag: 'ui',
    title: 'Mobile sticky run button',
    description: 'Fixed bottom bar on mobile with prominent run button + reset. Desktop controls hidden on small screens. Nav flattened.',
  },
  {
    id: 37,
    date: '2026-03-19',
    time: '05:20',
    tag: 'entity',
    title: 'Poet agent',
    description: 'Poet reads the metalog and scores candidate sentences by length variety, word overlap, adjective density, and tone. Selects top candidates for the source pool. Does not write. Page at /poet (not in nav). New category: curators (between cycle entities and observers).',
  },
  {
    id: 38,
    date: '2026-03-19',
    time: '05:20',
    tag: 'fix',
    title: 'Rulebook highlight fix',
    description: 'Fixed data-section-id placement on observers section. Rulebook comments now work correctly.',
  },
  {
    id: 39,
    date: '2026-03-19',
    time: '05:20',
    tag: 'ui',
    title: 'Three agent categories',
    description: 'Agents split into three groups: generation entities (run in pipeline), observers (annotate without changing), curators (shape inputs between sessions). Poet moved from observers to curators.',
  },
];
